## Splitting GENBANK Metadata qualifier 1 column generated by GENBANK_XML_PARSER to parse out voucher information.
#To parse the qualifier1 column from results of makeDataFrame_XML_voucher; make temp file of just qualifer1 column and read into R using command below...
## Marlene Hahn and Andrew Hipp, February 2013, as part of Carex project.

#STEP1:
	#indat <- readLines(file.choose())  ###or indat_2 (2 lines were missing from indat
	#source('spliting_metadata_genbank_tables.r')

#getSpec function
getSpec <- function(x) {
temp1 <- strsplit(x, "specimen_voucher")[[1]]
if(length(temp1) == 1) return("")
temp2 <- strsplit(temp1[2], 'db_xref')[[1]][1]
return(temp2)}

# Step2: using function and sapply to data.  using following command below.
	#voucher <- as.character(sapply(indat_2, getSpec))
# Step3: append voucher column to original table
	#append_metadata <-data.frame(metadata_table,voucher)
#Step 4: write out new table with voucher column
	#write.table(append_metadata, file = 'Cariceae_2013_02_28_voucher_appended.txt', sep = "|")  
	
	
# USE ANDREW HIPP'S PROGRAM TO HELP PARSE OUT COMPONENTS OF THE VOUCHER FIELD, SOME MANUAL MANIPULATIONS WILL BE NECESSARY.