amb2 <- function (base, forceToLower = TRUE, checkBase = TRUE, IUPAC = s2c("acgturymkswbdhvn"),
    u2t = TRUE, passthrough = c('-', 'n', '?'))
    ## modified from seqinr
    ## ahipp@mortonarb.org 2021-02-02
{
    if (missing(base))
        return(IUPAC)
    if (!is.character(base))
        stop("Character expected")
    if (nchar(base) != 1)
        stop("Single character expected")
    if (forceToLower)
        base <- tolower(base)
    if (checkBase)
        if (!(base %in% c(IUPAC, passthrough)))
            stop("IUPAC base expected")
    if (base %in% passthrough) return(base)
    if (base == "r")
        return(s2c("ag"))
    if (base == "y")
        return(s2c("ct"))
    if (base == "m")
        return(s2c("ac"))
    if (base == "k")
        return(s2c("gt"))
    if (base == "s")
        return(s2c("cg"))
    if (base == "w")
        return(s2c("at"))
    if (base == "b")
        return(s2c("cgt"))
    if (base == "d")
        return(s2c("agt"))
    if (base == "h")
        return(s2c("act"))
    if (base == "v")
        return(s2c("acg"))
    if (base == "n")
        return(s2c("acgt"))
    if (base == "u")
        if (u2t)
            return("t")
        else return("u")
    return(base)
}
